### PR TITLE
gRPC Server

### PR DESCRIPTION
**Pull request by compleatang**
At Monax we rely extensively on gRPC internal to our cluster. Indeed, `scalia` our document assembly build system knows no http at this point. gPRC is fast and very helpful for autogenerating clients in both typed and untyped languages.

I've restructured the repository slightly so that the http server and grpc servers can live alongside one another without a problem. They can be started independently as single servers (or as both).  

Structurally, both servers now have a *-server.js and *-handler.js structure where the *-server wraps the *-handler and returns the server object to server.js so that that file can control the units operationally. Both *-handler.js now rely upon the abstracted parser.js file (which was the core of the previous index.js, which was split into http-handler.js and parser.js). 

I'm not a node-al-ist, so please forgive the bad javascript.

FWIW, we're now auto-building a Dockerfile upon pushes to the @monax fork here -> https://quay.io/repository/monax/commonform-engine. I'll be finalizing the integration on the `scalia` document assembly coordination system this week and after that it would be great to tag this 1.0. 

There are a couple more things that I would like to do:

- [ ] add some extensibility to the signature pages functionality because within our build system we already know what the "blanks" on the signature pages are. as such I plan to fork https://github.com/commonform/ooxml-signature-pages and refactor it for our purposes.
- [ ] bit of cleanup on the *.proto file - I wanted to hold off until I do a bit more testing there.
- [ ] probably needs more tests - but I want to do some real world testing with some of our intrepid users before I think thru what exactly needs testing.

### CODE REVIEW

**Comment by kemitchell** [comment]
Is there no native Node.js library for gRPC?

**Comment by compleatang** [comment]
Not currently (which is hindering adoption in the browser). See note here -> https://github.com/grpc/grpc-node/blob/master/README.md#pure-javascript-client

**Comment by kemitchell** [comment]
Would we be better off writing a proxy to open.commonform.org in Go, and deploying as grpc.commonform.org?

**Comment by compleatang** [comment]
I'm not sure I'm following. Is this actually running as a server somewhere? These changes shouldn't affect that operation in any way as the gRPC side can be turned off. 

That said, I don't have strong views in either direction. We need the gRPC server and will run that in our cluster. I'm equally happy to keep it as a separate codebase or to keep the http and grpc sides relatively close with a common core.

**Comment by kemitchell** [comment]
> Is this actually running as a server somewhere? 

Yes. https://open.commonform.org. Note that GET requests, like visiting with your web browser, will just get redirected to this GitHub repo.

The idea is to provide this as a free service for those who prefer the JSON API to downloading and running the CLIs.

It sounds like you'd rather run whatever you'll depend on in your own cluster?

**Comment by compleatang** [comment]
THUS the name... (many times I'm quite dense). Personally I very much like the idea a lot of contributing a statically compiled go cli tool talking gRPC to a backend running at open.commonform.org as a replacement for node-based CLIs. 

In the shorter run, my intention, is that we will run a server in our cluster that will talk gRPC to our overarching document assembly framework. 

Another point in favor of a cohesive engine codebase is that given that server time and resources are sunk cost for us, I'm 100% happy to host one or more of the JSON HTTP servers on whatever URL. We currently run mumerous load-balanced instances for our document assembly framework so it would be simply a matter of us opening the port and then setting the CNAME/A records.

**Comment by kemitchell** [comment]
You could write a gRPC proxy in Golang, and deploy on your own infra together with a copy of open.commonform.org running on Node.

**Comment by compleatang** [comment]
More or less that's what this does but without an explicit hop on the other side of the proxy. In any event, a common core with different exposed servers may not be to the advantage so am happy to keep our work open but in a separate codebase.

**Comment by kemitchell** [comment]
This is good stuff. Don't toss it! But I want to make sure I'm not a drag on your work, any more than you are on mine.

**Comment by compleatang** [comment]
Oh, it's definitely not getting tossed. It's running in production :-) More seriously, though, if it makes sense to integrate a common core with two transport systems living in parallel (which is essentially what this is) then I'm happy to reopen later as we'll be maintaining this for the foreseeable future.

**Comment by kemitchell** [comment]
> Oh, it's definitely not getting tossed. It's running in production

Damn, son.

**Pull request closed without merging**
